### ISSUE TITLE
Issues about Dataset

### ISSUE THREAD

**Issue by davidwang200099** [satoshi-ikehata/Universal-PS-CVPR2022#2]
Mr Satoshi, I downloaded the dataset from dropbox, but found that ```depth.exr```, ```roughness.tif```, etc.  were lost in ```PS_WildTrain_zip``` folder. Could you tell me why?

**Comment by satoshi-ikehata** [comment]
To reduce the file size, I created individual zip archives by removing all data except the images and normals. This is because these images were simply used to render images, and they are not needed for training networks.

**Comment by davidwang200099** [comment]
Thank you for your reply, but personally I think ```depth.exr``` etc. can give more information, and may be used in future work. BTW three of the five zip files were corrupted, although they can be fixed to some extent.
